import PvNP.RealizableHardness.ActualSelectedComplementHC46OriginalApplication

#check PvNP.RealizableHardness.ActualSelectedComplementHC46OriginalApplication.selected_leaf_HC46_original
#print axioms PvNP.RealizableHardness.ActualSelectedComplementHC46OriginalApplication.selected_leaf_HC46_original
#check PvNP.RealizableHardness.ActualSelectedComplementHC46OriginalApplication.selected_leaf_failed_zoom_HC46_original
#print axioms PvNP.RealizableHardness.ActualSelectedComplementHC46OriginalApplication.selected_leaf_failed_zoom_HC46_original
