import * as fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defaults,save } from './migrate.mjs';
import { sha } from './archive.mjs';
async function main(){
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),c=JSON.parse(await fs.readFile(defaults.catalog,'utf8'));
const assessmentFile=path.join(repo,'docs/storage-review/2026-10-06/archive-catalog.json'),assessmentBytes=await fs.readFile(assessmentFile),assessment=JSON.parse(assessmentBytes),members=new Map(c.members.map(m=>[m.path,m]));
let matched=0,missing=0,mismatched=0;for(const a of assessment.archives){const m=members.get('realizable-cmmsa-hardness/'+a.path.replaceAll('\\','/'));if(!m)missing++;else if(m.bytes===a.bytes&&m.sha256===a.sha256)matched++;else mismatched++;}
const recovery=JSON.parse(await fs.readFile(path.join(defaults.state,'recovery/discovery.json'),'utf8'));
const coreVersions=new Set(c.chunks.map(x=>x.key+'\0'+x.version_id)),uniqueChunks=new Map();
for(const entry of recovery.catalogs){const raw=await fs.readFile(path.join(defaults.state,'recovery/source-catalogs',path.posix.basename(entry.catalog_key)));if(sha(raw)!==entry.catalog_sha256)throw Error('Protected recovery catalog changed');const catalog=JSON.parse(raw);for(const x of catalog.chunks)uniqueChunks.set(x.key+'\0'+x.version_id,x);}
const inventory=JSON.parse(await fs.readFile(path.join(defaults.state,'source-versions.json'),'utf8')),recoveryRows=inventory.rows.filter(r=>r.key.startsWith('migrations/cmmsa44-recovery-20261007/'));
const recoveryObjectTypes={catalog_json:0,encrypted_qarc:0,other:0,encrypted_versions_unreferenced_by_directory_catalogs:0};for(const r of recoveryRows){if(r.key.endsWith('.json'))recoveryObjectTypes.catalog_json++;else if(r.key.endsWith('.qarc')){recoveryObjectTypes.encrypted_qarc++;if(!uniqueChunks.has(r.key+'\0'+r.version))recoveryObjectTypes.encrypted_versions_unreferenced_by_directory_catalogs++;}else recoveryObjectTypes.other++;}
const namespaceCounts={};for(const m of c.members){const p=m.path.startsWith('codex-history/sessions/')?'codex-history/sessions':m.path.split('/')[0];namespaceCounts[p]=(namespaceCounts[p]??0)+1;}
const report={at:new Date().toISOString(),source_catalog_sha256:sha(await fs.readFile(defaults.catalog)),assessment_sha256:sha(assessmentBytes),historical_assessment:{archives:assessment.archives.length,bytes:assessment.archive_bytes,hash_matched_catalog_members:matched,missing_from_core_catalog:missing,hash_mismatches:mismatched,assessment_receipt_changed:false},core_namespace_member_counts:namespaceCounts,additional_recovery:{catalogs:recovery.catalogs.length,catalog_member_entries:recovery.catalogs.reduce((n,x)=>n+x.members,0),chunk_references:recovery.catalogs.reduce((n,x)=>n+x.chunks,0),chunk_reference_bytes:recovery.catalogs.reduce((n,x)=>n+x.bytes,0),unique_chunk_versions:uniqueChunks.size,unique_chunk_bytes:[...uniqueChunks.values()].reduce((n,x)=>n+x.bytes,0),reused_core_chunk_versions:[...uniqueChunks.keys()].filter(k=>coreVersions.has(k)).length,additional_unique_chunk_versions:[...uniqueChunks.keys()].filter(k=>!coreVersions.has(k)).length,owner:'S3154 CMMSA archive custody',gcp_project_move:false,compiler_or_experiment_run:false},external_ownership_proposals:[{surface:'igh-nonprofit-archive-485386182336-us-east-1',owner:'Archrealms/Passport nonprofit extension per ancestor AGENTS',disposition:'excluded from Quantyra archive transfer; route to its owner'},{surface:'cyint-codex-session-archive-485386182336-54c906d8',owner:'unresolved shared/CYINT custody',disposition:'S3151 root attribution; no contents read or copied by S3154'},{surface:'amazon-braket regional source buckets',owner:'S3151/S3155 quantum attribution',disposition:'separate owner; no hardware requests or bucket payload reads by S3154'}]};
report.additional_recovery.object_types=recoveryObjectTypes;await save(path.join(repo,'docs/aws-migration-2026-10-06/archive-ownership-findings.json'),report);console.log(JSON.stringify(report));
}
main().catch(()=>{console.error('Ownership metadata check failed; no protected contents printed');process.exitCode=1;});
