import * as fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defaults,SOURCE,DEST,save } from './migrate.mjs';
import { sha } from './archive.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../..'),out=path.join(repo,'docs/aws-migration-2026-10-06');
const read=p=>fs.readFile(p,'utf8').then(JSON.parse).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
const state=defaults.state;
const inventory=await read(path.join(state,'source-versions.json')),mapping=await read(path.join(state,'version-mapping.json')),core=await read(path.join(state,'verify-destination/verification.json')),recovery=await read(path.join(state,'recovery/verify-destination-receipt.json')),discovery=await read(path.join(state,'recovery/discovery.json')),copyAll=await read(path.join(state,'copy-all-receipt.json')),bounded=await read(path.join(state,'bounded-destination-receipt.json')),removed=await read(path.join(state,'temporary-copy-policy-removal.json'));
const protectedFiles=[defaults.catalog,path.join(state,'source-versions.json'),path.join(state,'version-mapping.json'),path.join(state,'successor-catalog.json'),path.join(state,'verify-source/verification.json'),path.join(state,'verify-destination/verification.json'),path.join(state,'recovery/discovery.json'),path.join(state,'recovery/verify-destination-receipt.json'),path.join(state,'recovery/activate-receipt.json'),path.join(state,'copy-all-receipt.json'),path.join(state,'bounded-source-receipt.json'),path.join(state,'bounded-destination-receipt.json'),path.join(state,'temporary-copy-policy-removal.json'),path.join(path.dirname(defaults.catalog),'research-archive-catalog.quantyra.json')];
const hashes=[];for(const file of protectedFiles){const bytes=await fs.readFile(file).catch(e=>{if(e.code==='ENOENT')return null;throw e;});if(bytes)hashes.push({artifact:path.relative(path.dirname(path.dirname(defaults.catalog)),file).replaceAll('\\','/'),bytes:bytes.length,sha256:sha(bytes)});}
const groups={};for(const r of inventory?.rows||[]){const p=r.key.split('/').slice(0,2).join('/');groups[p]??={versions:0,bytes:0};groups[p].versions++;groups[p].bytes+=r.bytes;}
const summary={at:new Date().toISOString(),story:'S3154',source_bucket:SOURCE,destination_bucket:DEST,source_versions:inventory?.rows.length??0,source_delete_markers:inventory?.rows.filter(x=>x.kind==='delete-marker').length??0,source_bytes:inventory?.rows.reduce((n,x)=>n+x.bytes,0)??0,groups,mapped_verified_versions:mapping?.filter(x=>x.verified).length??0,core:{complete:core?.complete??false,chunks:core?.chunks.length??0,members:core?.members??0,bounded_restore:core?.restored?{bytes:core.restored.bytes,sha256:core.restored.sha256}:null},recovery:{catalogs:discovery?.catalogs.length??0,discovered_members:discovery?.catalogs.reduce((n,x)=>n+x.members,0)??0,complete:recovery?.complete??false,authenticated_members:recovery?.catalogs.reduce((n,x)=>n+x.members,0)??0},all_bucket_copy:copyAll?.complete??false,independent_bounded_destination_restore:bounded??null,temporary_copy_bridge_removed:removed?.removed??false,key_custody:{key_exists:(await fs.stat(defaults.key)).size===32,key_changed_by_this_operator:false,key_copied_to_aws_or_git:false},source_retirement:{performed:false,decision_owner:'parent root under S3156',eligible:false},protected_artifact_hashes:hashes};
await save(path.join(out,'archive-evidence-summary.json'),summary);
const files=(await fs.readdir(here)).filter(n=>n!== 'node_modules'&&(/\.(mjs|md|json)$/.test(n)||n==='.gitignore'));
const artifacts=[];for(const n of files){const bytes=await fs.readFile(path.join(here,n));artifacts.push({path:'scripts/aws-archive-migration/'+n,bytes:bytes.length,sha256:sha(bytes)});}
for(const n of ['archive-worktree-audit.md','archive-evidence-summary.json']){const bytes=await fs.readFile(path.join(out,n));artifacts.push({path:'docs/aws-migration-2026-10-06/'+n,bytes:bytes.length,sha256:sha(bytes)});}
await save(path.join(out,'archive-artifact-hashes.json'),{algorithm:'SHA256',artifacts});
console.log(JSON.stringify({source_versions:summary.source_versions,mapped_verified_versions:summary.mapped_verified_versions,core_complete:summary.core.complete,recovery_complete:summary.recovery.complete,all_bucket_copy:summary.all_bucket_copy,temporary_copy_bridge_removed:summary.temporary_copy_bridge_removed,source_retired:false}));
