import PvNP.RealizableHardness.ActualSelectedComplementSpectral47OriginalApplication

#check PvNP.RealizableHardness.ActualSelectedComplementSpectral47OriginalApplication.selected_leaf_high_energy_le_spectral_original_application
#print axioms PvNP.RealizableHardness.ActualSelectedComplementSpectral47OriginalApplication.selected_leaf_high_energy_le_spectral_original_application
