import PvNP.RealizableHardness.ActualBinaryMatrixHC46A7CarrierParseval

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A7CarrierParseval.complex_carrier_parseval
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A7CarrierParseval.actualW6Derivative_energy_parseval
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A7CarrierParseval.complex_carrier_parseval
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A7CarrierParseval.actualW6Derivative_energy_parseval
