import PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11CanonicalTriple
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_canonical_Xbar_square
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_canonical_ambient_C
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_canonical_ambient_H
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_canonical_pullback

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11GlobalInitialEquiv
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11GlobalInitialEquiv

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11PositiveGlobalInitialEquiv
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11StrictLowerDegreeIH
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_actual_mixed_fourth_le_output_q

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_actual_mixed_fourth_le_actual_final_sum
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_weighted_actual_mixed_le_final_sum

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11NonzeroInitialEquiv
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_weighted_mixed_sum_le_actual_initial_sum

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11GlobalA9SourceEquiv

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_weighted_actual_A9_partition
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_weighted_mixed_sum_le_actual_final_fibers

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_full_A10_exponent_saving
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_actual_fixed_final_saved_charge

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_full_finite_ij_tail

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_all_actual_final_energy_w6
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_all_actual_final_energy_terminal

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_actual_final_fibers_le_post_tail_energy
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_original_weighted_mixed_bound
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_original_weighted_mixed_bound

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.a11_original_A7_positive_from_strict_IH
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.manuscript_A7_actual
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A11WeightedAggregate.manuscript_A7_actual
