import PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment

#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.matching_center_mass_eq_grassmann_beta
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.selected_actual_source_dimension_bound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.exists_dyadic_moment_exponent_window
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.selected_actual_analytic_rhs
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.selected_actual_HC_spectral_moment_bound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.selected_actual_material_moment_bound
#check PvNP.RealizableHardness.ActualFiniteMomentLpBounds.finite_sum_lpNorm_le
#check PvNP.RealizableHardness.ActualFiniteMomentLpBounds.appendAverage_lpNorm_le
#check PvNP.RealizableHardness.ActualSelectedSpectralParameters.selected_spectral_parameters

#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.matching_center_mass_eq_grassmann_beta
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.selected_actual_source_dimension_bound
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.exists_dyadic_moment_exponent_window
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.selected_actual_HC_spectral_moment_bound
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMoment.selected_actual_material_moment_bound
#print axioms PvNP.RealizableHardness.ActualFiniteMomentLpBounds.finite_sum_lpNorm_le
#print axioms PvNP.RealizableHardness.ActualFiniteMomentLpBounds.appendAverage_lpNorm_le
#print axioms PvNP.RealizableHardness.ActualSelectedSpectralParameters.selected_spectral_parameters
