import PvNP.RealizableHardness.ActualLeafLabelRankImageAlignment

#check PvNP.RealizableHardness.ActualLeafLabelRankImageAlignment.leafMatchBit_eq_matchingLeafSet
#check PvNP.RealizableHardness.ActualLeafLabelRankImageAlignment.leafMatchBit_fun_eq_matchingLeafSet
#check PvNP.RealizableHardness.ActualLeafLabelRankImageAlignment.actualLeafRankImage_eq_matchingLeafSet
#check PvNP.RealizableHardness.ActualLeafLabelRankImageAlignment.actualLeafRankImageIndicator_eq_matchingLeafSet
#check PvNP.RealizableHardness.ActualLeafLabelRankImageAlignment.actual_leaf_failed_zoom_gives_nominal_pseudorandom

#print axioms PvNP.RealizableHardness.ActualLeafLabelRankImageAlignment.leafMatchBit_eq_matchingLeafSet
#print axioms PvNP.RealizableHardness.ActualLeafLabelRankImageAlignment.actualLeafRankImage_eq_matchingLeafSet
#print axioms PvNP.RealizableHardness.ActualLeafLabelRankImageAlignment.actual_leaf_failed_zoom_gives_nominal_pseudorandom
