import PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment

open PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment
open PvNP.RealizableHardness.MatrixGrassmannIdentity

#check PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment.coordinateArrayBinaryMatrixEquiv
#check PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment.rawTF_eq_unconditional_binaryMatrix_mean
#check PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment.matrixMoment_eq_actualBinaryMatrixMoment
#check PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment.matchingStarMass_cast_le_twice_actualBinaryMatrixMoment

#print axioms PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment.coordinateArrayBinaryMatrixEquiv
#print axioms PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment.rawTF_eq_unconditional_binaryMatrix_mean
#print axioms PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment.matrixMoment_eq_actualBinaryMatrixMoment
#print axioms PvNP.RealizableHardness.ActualFixedFunctionalBinaryMatrixMoment.matchingStarMass_cast_le_twice_actualBinaryMatrixMoment
