import PvNP.RealizableHardness.ActualTaggedComplementIncidence

open PvNP.RealizableHardness.ActualTaggedComplementIncidence

#check uniform_sideLeafTuple_pushforward
#check side_fixedCenter_acceptance_mass_eq_full
#check complement_observed_atom_weight
#check sideConditionalDensity_eq_observedFullDensity
#check complementFullDensity_eq_observedFullDensity
#check ordinaryComplementStarDensity_eq_complementFullDensity
#check sideConditionalDensity_eq_ordinaryComplementStarDensity

#print axioms uniform_sideLeafTuple_pushforward
#print axioms side_fixedCenter_acceptance_mass_eq_full
#print axioms complement_observed_atom_weight
#print axioms sideConditionalDensity_eq_observedFullDensity
#print axioms complementFullDensity_eq_observedFullDensity
#print axioms ordinaryComplementStarDensity_eq_complementFullDensity
#print axioms sideConditionalDensity_eq_ordinaryComplementStarDensity
