import PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin

#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.local_manuscript_scale_eq_successMargin
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_success_scale_eq_successMargin
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rational_failure_threshold_exists
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rational_failure_eta_le_four_floor
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rational_low_HC_sum_bound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_low_HC_sum_bound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_low_HC46_constant_sum_bound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_exponent_is_signal_ratio_exponent
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_dyadic_ratio_eq_exponent
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_exponent_le_neg_one
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_factor_with_outer_two_le_one
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_selected_functional_beta_lower
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_selected_beta_controls_holder_loss
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_selected_same_witness_signal_and_holder_loss
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.rankProjection_all_levels_energy_eq
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.indicator_squared_mean_le_one
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rank_layer_energy_le_one
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_weighted_levels_le_max_weight
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_spectral_coefficient_le_tail
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_high_spectral_sum_le_tail
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_tail_guards_of_growth
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_tail_guards_of_margin_floor
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_tail_guards

#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.local_manuscript_scale_eq_successMargin
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rational_low_HC_sum_bound
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_low_HC46_constant_sum_bound
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_exponent_is_signal_ratio_exponent
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_dyadic_ratio_eq_exponent
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_factor_with_outer_two_le_one
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_selected_same_witness_signal_and_holder_loss
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.rankProjection_all_levels_energy_eq
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_high_spectral_sum_le_tail
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_tail_guards