import PvNP.RealizableHardness.ActualBinaryMatrixHC46A7Transfer

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A7Transfer

#check a7HybridQ
#check a7_constant_of_degree_zero
#check a7_filter_zero_of_positive_pair
#check a7_q_eq_zero_order
#check a7_fourth_eq_l2_of_degree_zero
#check manuscript_A7_degree_zero
#check a7_l2_slack
#check a7_terminal_factor
#check a7_zero_order_component
#check a7_zero_order_uniform
#check a7_pair_share_nonneg
#check a7_pair_shares_exhaust
#check a7_q_ge_l2
#check a7HybridQ_nonneg
#check a7_positive_of_mixed_bound
#check a7_derivative_fourth_zero_of_high
#check a7_triple_exponent_fits
#check a7_triple_share_exponent_fits
#check a7_mixed_sum_of_shares
#check a7_positive_of_overlapping_shares
#check a7MixedOutputFourth
#check a7_mixed_fourth_output
#check a7_mixed_output_fourth_typed
#check a7_mixed_output_fourth_coordinate
#check a7_mixed_output_coordinate_support
#check a7_mixed_coordinate_support
#check a7_output_energy_sq_le_component
#check a7_saturated_output_le_component
#check a7_saturated_fourth_le_share
#check a7_saturated_output_eq_energy_sq
#check a7_saturated_output_le_pool
#check a7_same_pair_parent_unique
#check a7_output_energy_carrier_cast
#check a7_ambientC_injective
#check a7_ambientH_injective
#check a7PullbackAt
#check a7_pullback_at_fourth
#check a7_pullback_at_injective
#check a7_parent_reconstructs_pair
#check a7_global_parent_unique
#check a7_carrier_energy_sq_sum_le
#check a7_saturated_same_field_output_sum_le
#check a7_saturated_same_field_fourth_sum_le
#check a7_saturated_carrier_fourth_sum_le
#check a7_saturated_pool_exponent_fits
#check a7CarrierParent
#check a7_carrier_parent_spec
#check a7_carrier_parent_fourth
#check a7_carrier_parent_unique
#check a7_saturated_carrier_all_pairs_output_sum_le
#check a7_saturated_carrier_all_pairs_fourth_sum_le
#check a7_saturated_all_pairs_fourth_sum_le
#check a7_saturated_weighted_all_pairs_le
#check a7_mixed_sum_degree_one
#check a7_degree_one_fourth_bound
#check a7_support_mono
#check a7OutputBinary
#check a7_output_binary_fourth
#check a7_low_output_fourth_le_output_q
#check a7_mixed_sum_order_split
#check a7_mixed_sum_le_allowance_add_lower

#print axioms a7_constant_of_degree_zero
#print axioms a7_q_eq_zero_order
#print axioms a7_fourth_eq_l2_of_degree_zero
#print axioms manuscript_A7_degree_zero
#print axioms a7_l2_slack
#print axioms a7_terminal_factor
#print axioms a7_zero_order_component
#print axioms a7_pair_share_nonneg
#print axioms a7_pair_shares_exhaust
#print axioms a7_q_ge_l2
#print axioms a7HybridQ_nonneg
#print axioms a7_positive_of_mixed_bound
#print axioms a7_derivative_fourth_zero_of_high
#print axioms a7_triple_exponent_fits
#print axioms a7_triple_share_exponent_fits
#print axioms a7_mixed_sum_of_shares
#print axioms a7_positive_of_overlapping_shares
#print axioms a7_mixed_fourth_output
#print axioms a7_mixed_output_fourth_typed
#print axioms a7_mixed_output_fourth_coordinate
#print axioms a7_mixed_output_coordinate_support
#print axioms a7_mixed_coordinate_support
#print axioms a7_output_energy_sq_le_component
#print axioms a7_saturated_output_le_component
#print axioms a7_saturated_fourth_le_share
#print axioms a7_saturated_output_eq_energy_sq
#print axioms a7_saturated_output_le_pool
#print axioms a7_same_pair_parent_unique
#print axioms a7_output_energy_carrier_cast
#print axioms a7_ambientC_injective
#print axioms a7_ambientH_injective
#print axioms a7_pullback_at_fourth
#print axioms a7_pullback_at_injective
#print axioms a7_parent_reconstructs_pair
#print axioms a7_global_parent_unique
#print axioms a7_carrier_energy_sq_sum_le
#print axioms a7_saturated_same_field_output_sum_le
#print axioms a7_saturated_same_field_fourth_sum_le
#print axioms a7_saturated_carrier_fourth_sum_le
#print axioms a7_saturated_pool_exponent_fits
#print axioms a7_carrier_parent_spec
#print axioms a7_carrier_parent_fourth
#print axioms a7_carrier_parent_unique
#print axioms a7_saturated_carrier_all_pairs_output_sum_le
#print axioms a7_saturated_carrier_all_pairs_fourth_sum_le
#print axioms a7_saturated_all_pairs_fourth_sum_le
#print axioms a7_saturated_weighted_all_pairs_le
#print axioms a7_mixed_sum_degree_one
#print axioms a7_degree_one_fourth_bound
#print axioms a7_support_mono
#print axioms a7_output_binary_fourth
#print axioms a7_low_output_fourth_le_output_q
#print axioms a7_mixed_sum_order_split
#print axioms a7_mixed_sum_le_allowance_add_lower
