import PvNP.RealizableHardness.ActualBinaryMatrixHC46A18DerivativeRankProjection

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A18DerivativeRankProjection

#check selected_frequency_rank_eq_carrier_rank_add_cost
#print axioms selected_frequency_rank_eq_carrier_rank_add_cost
#check selected_frequency_rank_eq_iff_residual
#print axioms selected_frequency_rank_eq_iff_residual
#check filteredCarrierFunction_rankProjection_eq_typed
#print axioms filteredCarrierFunction_rankProjection_eq_typed
#check complexFourierCoeff_character
#print axioms complexFourierCoeff_character
#check filteredCarrierFunction_character
#print axioms filteredCarrierFunction_character
#check filteredCarrierFunction_fourier_expansion
#print axioms filteredCarrierFunction_fourier_expansion
#check complexCarrierFourierCoeff_character
#print axioms complexCarrierFourierCoeff_character
#check typedComplexRankProjection_character
#print axioms typedComplexRankProjection_character
#check complexCarrierFourierCoeff_finset_sum
#print axioms complexCarrierFourierCoeff_finset_sum
#check typedComplexRankProjection_finset_sum
#print axioms typedComplexRankProjection_finset_sum
#check complexCarrierFourierCoeff_smul
#print axioms complexCarrierFourierCoeff_smul
#check typedComplexRankProjection_smul
#print axioms typedComplexRankProjection_smul
#check complexFourierCoeff_rankProjection
#print axioms complexFourierCoeff_rankProjection
#check complexRankProjection_idempotent
#print axioms complexRankProjection_idempotent
#check complexFourierCoeff_finset_sum
#print axioms complexFourierCoeff_finset_sum
#check complexFourierCoeff_smul
#print axioms complexFourierCoeff_smul
#check filteredCarrierFunction_finset_sum
#print axioms filteredCarrierFunction_finset_sum
#check filteredCarrierFunction_smul
#print axioms filteredCarrierFunction_smul
#check actual_derivative_rank_projection_zero_below_cost
#print axioms actual_derivative_rank_projection_zero_below_cost
#check typed_carrier_rank_projection_energy_le
#print axioms typed_carrier_rank_projection_energy_le
#check actual_derivative_rank_projection_energy_le
#print axioms actual_derivative_rank_projection_energy_le
#check filteredCarrierFunction_support_drop
#print axioms filteredCarrierFunction_support_drop
#check actualDerivativeCoordinate_support_drop
#print axioms actualDerivativeCoordinate_support_drop
