import PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport

#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.grassEquiv
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.pullbackSubspace
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.pulledSubspaceEquiv
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.map_le_map_coordinate_iff
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.pullbackDecodedPair
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinate_zoom_containment_iff
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinateZoomEquiv
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinate_agrees_iff
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinateAgreeingZoomEquiv
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinate_codim_eq
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinate_agreement_eq
#check PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinate_failure_of_source_failure

#print axioms PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.pullbackDecodedPair
#print axioms PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinateZoomEquiv
#print axioms PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinateAgreeingZoomEquiv
#print axioms PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinate_agreement_eq
#print axioms PvNP.RealizableHardness.ActualCoordinateZoomFailureTransport.coordinate_failure_of_source_failure
