import PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse

#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.filteredCarrierFunction
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.complexAmbientHybridFilter_bot_top
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.complexAmbientHybridFilter_bot_top
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.filteredCarrierFunction_bot_top
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.filteredCarrierFunction_bot_top
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.hyperplane_suffix_A1_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.hyperplane_suffix_A1_collapse
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.line_suffix_A1_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.line_suffix_A1_collapse
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_line_head_A1_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_line_head_A1_collapse
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_hyperplane_head_A1_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_hyperplane_head_A1_collapse
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_source_tower_A1_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_source_tower_A1_collapse

#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.filteredCarrierFunction_bot_top_base
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.filteredCarrierFunction_bot_top_base
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.zero_step_carrier_pointwise
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.zero_step_carrier_pointwise
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.zero_step_carrier_energy_mean
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.zero_step_carrier_energy_mean
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.bottom_top_typedProjection_coordinate
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.bottom_top_typedProjection_coordinate
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.bottom_top_frequency_rank
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.bottom_top_frequency_rank
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.bottom_top_frequency_trace
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.bottom_top_frequency_trace

#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.zero_step_coordinate_energy_mean
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.zero_step_coordinate_energy_mean
