import PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator

open PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator

#check PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.appendCoordinateArrayEquiv
#check PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.appendBinaryMatrix_columns
#check PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.appendBinaryMatrix_range_eq_span
#check PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.appendBinaryMatrix_injective_iff
#check PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.rawG_eq_rankImageBoolean_indicator
#check PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.rawF_eq_rankImageBoolean_append
#check PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.rawTF_eq_appendRankImageMean
#check PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.actualBinaryMatrixMoment_eq_actualAppendRankImageMoment
#check PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.matchingStarMass_cast_le_twice_actualAppendRankImageMoment

#print axioms PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.rawG_eq_rankImageBoolean_indicator
#print axioms PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.rawF_eq_rankImageBoolean_append
#print axioms PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.rawTF_eq_appendRankImageMean
#print axioms PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.actualBinaryMatrixMoment_eq_actualAppendRankImageMoment
#print axioms PvNP.RealizableHardness.ActualFixedFunctionalAppendOperator.matchingStarMass_cast_le_twice_actualAppendRankImageMoment
