import PvNP.RealizableHardness.ActualComplementCoordinateMassBridge

#check PvNP.RealizableHardness.ActualComplementCoordinateMassBridge.actualCoordinateDimensionBound
#check PvNP.RealizableHardness.ActualComplementCoordinateMassBridge.starLaw_pushforward_actual
#check PvNP.RealizableHardness.ActualComplementCoordinateMassBridge.matchingStarMass_actual_coordinate
#check PvNP.RealizableHardness.ActualComplementCoordinateMassBridge.matchingCenterMass_actual_coordinate

#print axioms PvNP.RealizableHardness.ActualComplementCoordinateMassBridge.actualCoordinateDimensionBound
#print axioms PvNP.RealizableHardness.ActualComplementCoordinateMassBridge.starLaw_pushforward_actual
#print axioms PvNP.RealizableHardness.ActualComplementCoordinateMassBridge.matchingStarMass_actual_coordinate
#print axioms PvNP.RealizableHardness.ActualComplementCoordinateMassBridge.matchingCenterMass_actual_coordinate
