import PvNP.RealizableHardness.ActualStarFixedCenterScalarClosure

namespace PvNP.RealizableHardness.ActualStarFixedCenterScalarClosureChecks

#check PvNP.RealizableHardness.ActualStarFixedCenterScalarClosure.supportStratifiedBound_le_powerRatio
#check PvNP.RealizableHardness.ActualStarFixedCenterScalarClosure.powerRatio_lt_threshold
#check PvNP.RealizableHardness.ActualStarFixedCenterScalarClosure.fixedCenter_badEvent_mass_lt_threshold

#print axioms PvNP.RealizableHardness.ActualStarFixedCenterScalarClosure.supportStratifiedBound_le_powerRatio
#print axioms PvNP.RealizableHardness.ActualStarFixedCenterScalarClosure.powerRatio_lt_threshold
#print axioms PvNP.RealizableHardness.ActualStarFixedCenterScalarClosure.fixedCenter_badEvent_mass_lt_threshold

end PvNP.RealizableHardness.ActualStarFixedCenterScalarClosureChecks
