import PvNP.RealizableHardness.ActualStarFixedCenterNumericalClosure

namespace PvNP.RealizableHardness.ActualStarFixedCenterNumericalClosureChecks

#check PvNP.RealizableHardness.ActualStarFixedCenterNumericalClosure.supportStratifiedBound
#check PvNP.RealizableHardness.ActualStarFixedCenterNumericalClosure.candidateSum_le_supportStratifiedBound
#check PvNP.RealizableHardness.ActualStarFixedCenterNumericalClosure.fixedCenter_badEvent_mass_le_supportStratifiedBound

#print axioms PvNP.RealizableHardness.ActualStarFixedCenterNumericalClosure.candidateSum_le_supportStratifiedBound
#print axioms PvNP.RealizableHardness.ActualStarFixedCenterNumericalClosure.fixedCenter_badEvent_mass_le_supportStratifiedBound

end PvNP.RealizableHardness.ActualStarFixedCenterNumericalClosureChecks
