import PvNP.RealizableHardness.ActualStarFixedCenterFirstMoment

namespace PvNP.RealizableHardness.ActualStarFixedCenterFirstMomentChecks

#check PvNP.RealizableHardness.ActualStarFixedCenterFirstMoment.CandidateCatalog
#check PvNP.RealizableHardness.ActualStarFixedCenterFirstMoment.candidateLineEvent
#check PvNP.RealizableHardness.ActualStarFixedCenterFirstMoment.fixedCenterBadEvent
#check PvNP.RealizableHardness.ActualStarFixedCenterFirstMoment.fixedCenter_badEvent_subset_catalogUnion
#check PvNP.RealizableHardness.ActualStarFixedCenterFirstMoment.fixedCenter_badEvent_mass_le_candidateSum

#print axioms PvNP.RealizableHardness.ActualStarFixedCenterFirstMoment.fixedCenter_badEvent_subset_catalogUnion
#print axioms PvNP.RealizableHardness.ActualStarFixedCenterFirstMoment.fixedCenter_badEvent_mass_le_candidateSum

end PvNP.RealizableHardness.ActualStarFixedCenterFirstMomentChecks
