import PvNP.RealizableHardness.ActualBinaryMatrixHC46A7Transfer

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A7Transfer

#check a7HybridQ
#check a7_constant_of_degree_zero
#check a7_filter_zero_of_positive_pair
#check a7_q_eq_zero_order
#check a7_fourth_eq_l2_of_degree_zero
#check manuscript_A7_degree_zero
#check a7_l2_slack
#check a7_terminal_factor
#check a7_zero_order_component
#check a7_zero_order_uniform
#check a7_q_ge_l2
#check a7HybridQ_nonneg
#check a7_positive_of_mixed_bound
#check a7_derivative_fourth_zero_of_high
#check a7_triple_exponent_fits
#check a7_triple_share_exponent_fits
#check a7_mixed_sum_of_shares
#check a7_positive_of_overlapping_shares
#check a7MixedOutputFourth
#check a7_mixed_fourth_output
#check a7_mixed_output_coordinate_support

#print axioms a7_constant_of_degree_zero
#print axioms a7_q_eq_zero_order
#print axioms a7_fourth_eq_l2_of_degree_zero
#print axioms manuscript_A7_degree_zero
#print axioms a7_l2_slack
#print axioms a7_terminal_factor
#print axioms a7_zero_order_component
#print axioms a7_q_ge_l2
#print axioms a7HybridQ_nonneg
#print axioms a7_positive_of_mixed_bound
#print axioms a7_derivative_fourth_zero_of_high
#print axioms a7_triple_exponent_fits
#print axioms a7_triple_share_exponent_fits
#print axioms a7_mixed_sum_of_shares
#print axioms a7_positive_of_overlapping_shares
#print axioms a7_mixed_fourth_output
#print axioms a7_mixed_output_coordinate_support
