import PvNP.RealizableHardness.ActualStarAcceptedGoodMass

/-! Checks cite `selected_transverseLeaf_accepted_rankGood`. That theorem is
not the manuscript physical acceptance inequality: its acceptance event is
the whole sample. The stop is
`lean/reviews/2026-09-26-accepted-good-mass-stop.md`. -/

namespace PvNP.RealizableHardness.ActualStarAcceptedGoodMassChecks

#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.successMargin
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.successMargin_half
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.starLaw_bad_mass_lt_threshold
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.sameExperiment_accepted_rankGood
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.leafT_le_two_mul_h
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.selected_hBlock_le_blocks
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.physical_domainDraw_eq_center_extension_law
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.selectedLeafEquiv
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.jointLaw_eq_starLaw
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.jointLaw_draws_center
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.selected_joint_accepted_rankGood
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.questionCenterOf_quotientImage
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.physicalJoint_draws_center
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.selected_physicalJoint_accepted_rankGood
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.presentedOfTransverseLeaf
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.transverseLeafAccept_holds
#check PvNP.RealizableHardness.ActualStarAcceptedGoodMass.selected_transverseLeaf_accepted_rankGood
#print axioms PvNP.RealizableHardness.ActualStarAcceptedGoodMass.starLaw_bad_mass_lt_threshold
#print axioms PvNP.RealizableHardness.ActualStarAcceptedGoodMass.sameExperiment_accepted_rankGood
#print axioms PvNP.RealizableHardness.ActualStarAcceptedGoodMass.jointLaw_draws_center
#print axioms PvNP.RealizableHardness.ActualStarAcceptedGoodMass.physical_domainDraw_eq_center_extension_law
#print axioms PvNP.RealizableHardness.ActualStarAcceptedGoodMass.selected_joint_accepted_rankGood
#print axioms PvNP.RealizableHardness.ActualStarAcceptedGoodMass.questionCenterOf_quotientImage
#print axioms PvNP.RealizableHardness.ActualStarAcceptedGoodMass.physicalJoint_draws_center
#print axioms PvNP.RealizableHardness.ActualStarAcceptedGoodMass.selected_physicalJoint_accepted_rankGood
#print axioms PvNP.RealizableHardness.ActualStarAcceptedGoodMass.selected_transverseLeaf_accepted_rankGood

end PvNP.RealizableHardness.ActualStarAcceptedGoodMassChecks
