import PvNP.RealizableHardness.ActualTaggedComplementStarDensityBound

open PvNP.RealizableHardness.ActualTaggedComplementStarDensityBound
open PvNP.RealizableHardness.ActualTaggedComplementStarLeafMassBound

#check actualLeafMassAtCenter_le_starLeafMassAtCenter
#print axioms actualLeafMassAtCenter_le_starLeafMassAtCenter

#check actualComplementSideDensity_le_StarDensity
#print axioms actualComplementSideDensity_le_StarDensity

#check ordinaryComplementStarDensity_eq_uniform_actualComplementSideDensity
#print axioms ordinaryComplementStarDensity_eq_uniform_actualComplementSideDensity

#check sideConditionalDensity_le_uniformComplement_average_StarDensity
#print axioms sideConditionalDensity_le_uniformComplement_average_StarDensity
