import PvNP.RealizableHardness.ActualStarBadMassWitness

namespace PvNP.RealizableHardness.ActualStarBadMassWitnessChecks

#check PvNP.RealizableHardness.ActualStarBadMassWitness.quotientVectorLine
#check PvNP.RealizableHardness.ActualStarBadMassWitness.exactSupport_relation_mem_supportedLineEvent
#check PvNP.RealizableHardness.ActualStarBadMassWitness.not_jointlyDirect_has_supportedLineEvent
#check PvNP.RealizableHardness.ActualStarBadMassWitness.fixedCenter_relationLineEvent_mass
#check PvNP.RealizableHardness.ActualStarKernelSupport.kernelWitness_has_exact_support_relation
#check PvNP.RealizableHardness.ActualStarRelationCount.nonzeroRelation_card_le_power
#check PvNP.RealizableHardness.ActualStarExtensionProduct.fixedCenter_supportedLine_eventMass
#print axioms PvNP.RealizableHardness.ActualStarBadMassWitness.exactSupport_relation_mem_supportedLineEvent
#print axioms PvNP.RealizableHardness.ActualStarBadMassWitness.not_jointlyDirect_has_supportedLineEvent
#print axioms PvNP.RealizableHardness.ActualStarBadMassWitness.fixedCenter_relationLineEvent_mass

end PvNP.RealizableHardness.ActualStarBadMassWitnessChecks
