import PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality

open PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality

#check PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.pairing_appendBinaryMatrix
#check PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.character_appendBinaryMatrix
#check PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.appendAverage_character
#check PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.appendAverage_character_mul_eq_zero
#check PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.uniformMean_sum
#check PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.uniformMean_const_mul
#check PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.appendAverage_rankProjection_sum
#check PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.uniformMean_appendAverage_rankProjection_mul_rankProjection_eq_zero

#print axioms PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.appendAverage_character_mul_eq_zero
#print axioms PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.appendAverage_rankProjection_sum
#print axioms PvNP.RealizableHardness.ActualAppendFourierCrossLevelOrthogonality.uniformMean_appendAverage_rankProjection_mul_rankProjection_eq_zero
