import PvNP.RealizableHardness.ActualOriginalFailureAnalyticCaller

#check PvNP.RealizableHardness.ActualOriginalFailureAnalyticCaller.source_failed_zoom_to_selected_coordinate
#check PvNP.RealizableHardness.ActualOriginalFailureAnalyticCaller.selected_actual_material_moment_bound_large_dyadic_from_source_failure

#print axioms PvNP.RealizableHardness.ActualOriginalFailureAnalyticCaller.source_failed_zoom_to_selected_coordinate
#print axioms PvNP.RealizableHardness.ActualOriginalFailureAnalyticCaller.selected_actual_material_moment_bound_large_dyadic_from_source_failure
