import PvNP.RealizableHardness.ActualStarSupportCatalog

namespace PvNP.RealizableHardness.ActualStarSupportCatalogChecks

#check PvNP.RealizableHardness.ActualStarSupportCatalog.SupportRelation
#check PvNP.RealizableHardness.ActualStarSupportCatalog.supportRelationEquiv
#check PvNP.RealizableHardness.ActualStarSupportCatalog.supportRelation_card_le_power
#check PvNP.RealizableHardness.ActualStarSupportCatalog.supportRelationLines
#check PvNP.RealizableHardness.ActualStarSupportCatalog.supportRelation_mem_supportedLineEvent
#check PvNP.RealizableHardness.ActualStarSupportCatalog.not_jointlyDirect_has_catalogEvent

#print axioms PvNP.RealizableHardness.ActualStarSupportCatalog.supportRelationEquiv
#print axioms PvNP.RealizableHardness.ActualStarSupportCatalog.supportRelation_card_le_power
#print axioms PvNP.RealizableHardness.ActualStarSupportCatalog.supportRelation_mem_supportedLineEvent
#print axioms PvNP.RealizableHardness.ActualStarSupportCatalog.not_jointlyDirect_has_catalogEvent

end PvNP.RealizableHardness.ActualStarSupportCatalogChecks
