import PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin

#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_star_density_eq_coordinate_of_tables
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.transported_complement_star_density_eq_coordinate
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_coordinate_score_of_actual_complement_score
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.local_manuscript_scale_eq_successMargin
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_success_scale_eq_successMargin
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rational_failure_threshold_exists
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rational_failure_eta_le_four_floor
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rational_low_HC_sum_bound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_low_HC_sum_bound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_low_HC46_constant_sum_bound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_low_HC_dyadic_envelope
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.sourceLowHCHeightFloor
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_low_HC_floor
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_exponent_is_signal_ratio_exponent
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_dyadic_ratio_eq_exponent
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_exponent_le_neg_one
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_factor_with_outer_two_le_one
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_same_witness_low_HC_signal_bound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_selected_functional_beta_lower
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_selected_beta_controls_holder_loss
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_selected_same_witness_signal_and_holder_loss
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.rankProjection_all_levels_energy_eq
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.indicator_squared_mean_le_one
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rank_layer_energy_le_one
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_weighted_levels_le_max_weight
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_spectral_coefficient_le_tail
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_high_spectral_sum_le_tail
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_tail_guards_of_growth
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_tail_guards_of_margin_floor
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_tail_guards
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.actual_side_score_selects_coordinate_complement
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.actual_side_score_selects_same_coordinate_functional

#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_star_density_eq_coordinate_of_tables
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.transported_complement_star_density_eq_coordinate
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_coordinate_score_of_actual_complement_score
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.local_manuscript_scale_eq_successMargin
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_rational_low_HC_sum_bound
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_low_HC46_constant_sum_bound
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_low_HC_dyadic_envelope
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_low_HC_floor
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_exponent_is_signal_ratio_exponent
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_dyadic_ratio_eq_exponent
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.source_low_relative_factor_with_outer_two_le_one
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_same_witness_low_HC_signal_bound
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.ordinary_selected_same_witness_signal_and_holder_loss
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.rankProjection_all_levels_energy_eq
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_high_spectral_sum_le_tail
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_tail_guards
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.actual_side_score_selects_coordinate_complement
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.actual_side_score_selects_same_coordinate_functional
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_weighted_signal_bundle
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_coordinate_score_bundle
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.original_score_and_failure_select_same_actual_moment_witness
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.original_score_and_failure_select_same_actual_moment_witness
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_fixed_functional_low_HC_signal_bound
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_fixed_functional_low_HC_signal_bound

#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_additive_signal_dominates_dyadic
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_first_signal_eq_dyadic
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_matching_center_mass_le_one
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_total_analytic_budget_contradicts_signal
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_fixed_functional_rhs_lt_matching_mass
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_additive_signal_dominates_dyadic
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_first_signal_eq_dyadic
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_matching_center_mass_le_one
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_total_analytic_budget_contradicts_signal
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.selected_actual_fixed_functional_rhs_lt_matching_mass

#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.original_score_and_failure_same_witness_contradiction
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.original_score_and_failure_same_witness_contradiction

#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.original_score_and_failure_yields_bad_zoom
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticMargin.original_score_and_failure_yields_bad_zoom
