import PvNP.RealizableHardness.ActualRankImageRightBasisInvariance

#check PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.matrix_toLin_mul_right_range_injective
#check PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.rankImageBoolean_mul_right_eq
#check PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.indicator_rankImageBoolean_mul_right_eq
#check PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.actualCenterIndicator_mul_right_eq
#check PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.actualLeafIndicator_mul_right_eq
#check PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.actualLeafAppendAverage_mul_right_eq
#check PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.actualAppendRankImageMoment_actualLeaf_mul_right_eq

#print axioms PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.matrix_toLin_mul_right_range_injective
#print axioms PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.rankImageBoolean_mul_right_eq
#print axioms PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.actualLeafAppendAverage_mul_right_eq
#print axioms PvNP.RealizableHardness.ActualRankImageRightBasisInvariance.actualAppendRankImageMoment_actualLeaf_mul_right_eq
