import PvNP.RealizableHardness.ActualSelectedCmmsaPaddedRunStackEq

namespace PvNP.RealizableHardness.ActualSelectedCmmsaPaddedRunStackEqChecks

open PvNP.RealizableHardness.ActualSelectedCmmsaPaddedRunStackEq

#check packedFracPaddedRunOutputTag_eq_checked_of_policy_true
#check packedFracPaddedRunOutputTag_eq_checked_of_producer
#check packedFracPaddedRunOutputTag_eq_checkedOutput_of

#print axioms packedFracPaddedRunOutputTag_eq_checked_of_policy_true
#print axioms packedFracPaddedRunOutputTag_eq_checked_of_producer
#print axioms packedFracPaddedRunOutputTag_eq_checkedOutput_of

end PvNP.RealizableHardness.ActualSelectedCmmsaPaddedRunStackEqChecks
