import PvNP.RealizableHardness.ActualFiniteDegreeFourierReconstruction

open PvNP.RealizableHardness.ActualFiniteDegreeFourierReconstruction

#check complexRankProjection_zero_of_width_lt
#print axioms complexRankProjection_zero_of_width_lt
#check ComplexFourierSupportedThrough
#check complexRankProjection_fourier_support
#print axioms complexRankProjection_fourier_support
#check complexRankProjection_supportedThrough
#print axioms complexRankProjection_supportedThrough
#check complexRankProjection_zero_of_level_gt
#print axioms complexRankProjection_zero_of_level_gt
#check complexRankProjection_zero_of_not_mem_rank_image
#print axioms complexRankProjection_zero_of_not_mem_rank_image
#check complexRankProjection_reconstruct_range
#print axioms complexRankProjection_reconstruct_range
#check complexRankProjection_reconstruct_range_of_support
#print axioms complexRankProjection_reconstruct_range_of_support
