import PvNP.RealizableHardness.ActualBinaryMatrixHC46A18ActualGlobalBridge

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A18ActualGlobalBridge

#check translateActualRestriction
#check translateActualRestriction_order
#print axioms translateActualRestriction_order
#check translateActualRestriction_fibre_mem
#print axioms translateActualRestriction_fibre_mem
#check translateActualRestriction_fibre
#print axioms translateActualRestriction_fibre
#check fibreEnergy_translateActualRestriction
#print axioms fibreEnergy_translateActualRestriction
#check translate_actual_global
#print axioms translate_actual_global
#check complexLineAverage_actual_global
#print axioms complexLineAverage_actual_global
#check complexLineAverage_actual_global_le_two
#print axioms complexLineAverage_actual_global_le_two
