import PvNP.RealizableHardness.ActualTypedABCanonicalProjection

#check PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_line_successor_projection
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_line_successor_projection
#check PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_hyperplane_successor_projection
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_hyperplane_successor_projection
