import PvNP.RealizableHardness.ActualBinaryMatrixHC46A18SourceGlobal

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A18SourceGlobal
#check actual_source_parameter_nonneg
#print axioms actual_source_parameter_nonneg

#check restrictedFunctionalKernel_finrank_drop
#print axioms restrictedFunctionalKernel_finrank_drop
#check codimension_drop_of_one_dim_extension
#print axioms codimension_drop_of_one_dim_extension
#check actual_expanded_outside_column_energy_le_two
#print axioms actual_expanded_outside_column_energy_le_two
#check stableSourceSampleMap
#check stableSourceCoordinatesEquiv
#print axioms stableSourceCoordinatesEquiv
#check uniformMean_product_fst
#print axioms uniformMean_product_fst
#check stableSource_uniformMean_eq
#print axioms stableSource_uniformMean_eq
#check actual_stable_source_energy_le
#print axioms actual_stable_source_energy_le
#check actual_expanded_source_coordinates_equiv
#print axioms actual_expanded_source_coordinates_equiv
#check actual_expanded_source_coordinates_coe
#print axioms actual_expanded_source_coordinates_coe
#check actual_expanded_source_matrix_formula
#print axioms actual_expanded_source_matrix_formula
#check actual_expanded_source_mean_eq_conditional
#print axioms actual_expanded_source_mean_eq_conditional
#check outsideMap_subtype_mean_eq_filter
#print axioms outsideMap_subtype_mean_eq_filter
#check actual_expanded_source_energy_le_two
#print axioms actual_expanded_source_energy_le_two
#check stable_expanded_source_mixture_le_two
#print axioms stable_expanded_source_mixture_le_two
#check actual_A18_source_branch_mixture_energy_le_two
#print axioms actual_A18_source_branch_mixture_energy_le_two
#check quotientCosetColumnEquiv
#print axioms quotientCosetColumnEquiv
#check quotientCosetFibreEquiv
#print axioms quotientCosetFibreEquiv
#check quotientCosetFibre_card
#print axioms quotientCosetFibre_card
#check quotientCosetColumnProductEquiv
#print axioms quotientCosetColumnProductEquiv
#check quotientCosetColumnProduct_sum
#print axioms quotientCosetColumnProduct_sum
#check quotientCoset_partition_mean_le_two
#print axioms quotientCoset_partition_mean_le_two
#check actualFibreQuotientHomEquiv_symm_matrix
#print axioms actualFibreQuotientHomEquiv_symm_matrix

#check quotientCosetFibreEquiv_extension
#print axioms quotientCosetFibreEquiv_extension

#check quotientCosetSourceFibreEquiv
#print axioms quotientCosetSourceFibreEquiv

#check stableSourceSampleMap_coe
#print axioms stableSourceSampleMap_coe

#check actual_stable_source_matrix_formula
#print axioms actual_stable_source_matrix_formula
#check actual_stable_source_energy_le_of_coordinates
#print axioms actual_stable_source_energy_le_of_coordinates

#check actual_expanded_source_coordinates_coe_uniform
#print axioms actual_expanded_source_coordinates_coe_uniform
#check actual_expanded_source_energy_le_two_common_coordinates
#print axioms actual_expanded_source_energy_le_two_common_coordinates
#check actual_source_quotient_coset_mean_le_two
#print axioms actual_source_quotient_coset_mean_le_two
#check actual_source_all_columns_mean_le_two
#print axioms actual_source_all_columns_mean_le_two
#check normSq_finite_average_le
#print axioms normSq_finite_average_le
#check normSq_iterated_average_le
#print axioms normSq_iterated_average_le
#check actual_fixed_functional_line_average_energy_le_two
#print axioms actual_fixed_functional_line_average_energy_le_two
#check quotientSampleOutput_eq_parent_add_line
#print axioms quotientSampleOutput_eq_parent_add_line
#check restrictedFunctionalReference_extends
#print axioms restrictedFunctionalReference_extends
#check restrictedFunctionalExtensionEquiv
#print axioms restrictedFunctionalExtensionEquiv
#check globalFunctionalRestrictionEquiv
#print axioms globalFunctionalRestrictionEquiv
