import PvNP.RealizableHardness.ActualStarExtensionProduct

namespace PvNP.RealizableHardness.ActualStarExtensionProductChecks

#check PvNP.RealizableHardness.ActualStarExtensionProduct.eventMass_uniform_filter_function
#check PvNP.RealizableHardness.ActualStarExtensionProduct.uniformFunction_cylinder_eventMass
#check PvNP.RealizableHardness.ActualStarExtensionProduct.extensionTupleLaw
#check PvNP.RealizableHardness.ActualStarExtensionProduct.extensionTupleLaw_atom
#check PvNP.RealizableHardness.ActualStarExtensionProduct.supportedLineEvent
#check PvNP.RealizableHardness.ActualStarExtensionProduct.fixedCenter_supportedLine_eventMass
#check PvNP.RealizableHardness.ActualStarExtensionProduct.fixedCenter_emptySupport_eventMass
#check PvNP.RealizableHardness.ActualStarExtensionProduct.fixedCenter_supportedLine_eventMass_zeroIncrement
#print axioms PvNP.RealizableHardness.ActualStarExtensionProduct.uniformFunction_cylinder_eventMass
#print axioms PvNP.RealizableHardness.ActualStarExtensionProduct.fixedCenter_supportedLine_eventMass
#print axioms PvNP.RealizableHardness.ActualStarExtensionProduct.fixedCenter_supportedLine_eventMass_zeroIncrement

end PvNP.RealizableHardness.ActualStarExtensionProductChecks
