import PvNP.RealizableHardness.ActualTypedABCanonicalRankProjectionCollapse

#check PvNP.RealizableHardness.ActualTypedABCanonicalRankProjectionCollapse.canonical_source_rank_projection_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalRankProjectionCollapse.canonical_source_rank_projection_collapse
