import PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6ActualF2Pairs
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6ActualComplexF2Remainder
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6_actual_complex_square_fourierCoeff
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6_actual_complex_fourth_moment_parseval
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6_actual_complex_convolution_partition
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6_actual_fourth_moment_le_f1_plus_f2

#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6_actual_complex_square_fourierCoeff
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6_actual_complex_fourth_moment_parseval
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6_actual_complex_convolution_partition
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6Moment.dr6_actual_fourth_moment_le_f1_plus_f2
