import PvNP.RealizableHardness.ActualBinaryMatrixHC46A7PredecessorCount

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A7PredecessorCount.transposeMap
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A7PredecessorCount.w6_predecessor_range_decomposition
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A7PredecessorCount.w6_predecessor_ker_le
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A7PredecessorCount.w6_predecessor_range_decomposition
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A7PredecessorCount.w6_predecessor_ker_le
