import PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection

#check PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.exists_functional_extending_disjoint_pair
#print axioms PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.exists_functional_extending_disjoint_pair
#check PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.exists_uniform_match_mass_ge
#print axioms PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.exists_uniform_match_mass_ge
#check PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.exists_questionCenter_baseFunctional
#print axioms PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.exists_questionCenter_baseFunctional
#check PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.leaf_agrees_with_base_on_sup
#print axioms PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.leaf_agrees_with_base_on_sup
#check PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.matchingFunctionalFiber_card
#print axioms PvNP.RealizableHardness.ActualStarAffineFunctionalSelectionForceSelection.matchingFunctionalFiber_card
