import PvNP.RealizableHardness.ActualOriginalFailureFixedMomentCaller

#check PvNP.RealizableHardness.ActualOriginalFailureFixedMomentCaller.fixedMomentK
#check PvNP.RealizableHardness.ActualOriginalFailureFixedMomentCaller.fixedMomentP
#check PvNP.RealizableHardness.ActualOriginalFailureFixedMomentCaller.fixed_moment_scale_facts
#check PvNP.RealizableHardness.ActualOriginalFailureFixedMomentCaller.selected_actual_fixed_moment_bound_from_source_failure

#print axioms PvNP.RealizableHardness.ActualOriginalFailureFixedMomentCaller.fixed_moment_scale_facts
#print axioms PvNP.RealizableHardness.ActualOriginalFailureFixedMomentCaller.selected_actual_fixed_moment_bound_from_source_failure