import PvNP.RealizableHardness.ActualBinaryMatrixHC46FourierA16

open PvNP.RealizableHardness.ActualBinaryMatrixHC46FourierA16

#check rankProjection_fourier_support
#check rankProjection_inner_eq_zero
#check rankProjection_finite_energy_sum
#check rankProjection_reconstruct
#check mixedCoordinateDerivativeChain_re_fourier_support
#check mixedCoordinateDerivativeChain_im_fourier_support
#check mixedCoordinateDerivativeChain_re_orthogonal
#check mixedCoordinateDerivativeChain_im_orthogonal
#check mixedCoordinateDerivativeChain_complex_orthogonal
#print axioms rankProjection_fourier_support
#print axioms rankProjection_inner_eq_zero
#print axioms rankProjection_finite_energy_sum
#print axioms rankProjection_reconstruct
#print axioms mixedCoordinateDerivativeChain_re_fourier_support
#print axioms mixedCoordinateDerivativeChain_im_fourier_support
#print axioms mixedCoordinateDerivativeChain_re_orthogonal
#print axioms mixedCoordinateDerivativeChain_im_orthogonal
#print axioms mixedCoordinateDerivativeChain_complex_orthogonal
