import PvNP.RealizableHardness.ActualBinaryMatrixHC46A20SquareSupport

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A20SquareSupport

#check carrierComplexFourierSupportedThrough_mul
#print axioms carrierComplexFourierSupportedThrough_mul
#check carrierComplexFourierSupportedThrough_square
#print axioms carrierComplexFourierSupportedThrough_square
#check filteredCarrierFunction_supportedThrough
#print axioms filteredCarrierFunction_supportedThrough
#check complexAmbientAffineRestrict_fourier_expansion
#print axioms complexAmbientAffineRestrict_fourier_expansion
#check complexAmbientAffineRestrict_supportedThrough
#print axioms complexAmbientAffineRestrict_supportedThrough
#check complexAmbientAffineRestrict_square
#print axioms complexAmbientAffineRestrict_square
#check filteredCarrierFunction_square_supportedThrough
#print axioms filteredCarrierFunction_square_supportedThrough
#check complexAmbientAffineRestrict_square_supportedThrough
#print axioms complexAmbientAffineRestrict_square_supportedThrough
#check rawRestriction_composition_energy
#print axioms rawRestriction_composition_energy
