import PvNP.RealizableHardness.ActualSelectedHighEnergyTail

#check PvNP.RealizableHardness.ActualSelectedHighEnergyTail.rankProjection_all_levels_energy_eq
#check PvNP.RealizableHardness.ActualSelectedHighEnergyTail.indicator_squared_mean_le_one
#check PvNP.RealizableHardness.ActualSelectedHighEnergyTail.selected_rank_layer_energy_le_one
#check PvNP.RealizableHardness.ActualSelectedHighEnergyTail.selected_weighted_levels_le_max_weight
#check PvNP.RealizableHardness.ActualSelectedHighEnergyTail.selected_spectral_coefficient_le_tail
#check PvNP.RealizableHardness.ActualSelectedHighEnergyTail.selected_actual_high_spectral_sum_le_tail

#print axioms PvNP.RealizableHardness.ActualSelectedHighEnergyTail.rankProjection_all_levels_energy_eq
#print axioms PvNP.RealizableHardness.ActualSelectedHighEnergyTail.selected_weighted_levels_le_max_weight
#print axioms PvNP.RealizableHardness.ActualSelectedHighEnergyTail.selected_spectral_coefficient_le_tail
#print axioms PvNP.RealizableHardness.ActualSelectedHighEnergyTail.selected_actual_high_spectral_sum_le_tail