name = "realizable_hardness"
version = "0.1.0"
defaultTargets = ["PvNP"]

[[require]]
name = "complexitylib"
git = "https://github.com/SamuelSchlesinger/complexitylib"
rev = "6c248df7859f2f245e731c1e07057bf69d165fe2"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "e06eff5f95374108acfaf19f1ff7473aa7771df2"

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib"
rev = "d9be64196bf145edd019f1ccfeaee0c11166ba6b"

[[lean_lib]]
name = "PvNP"
srcDir = "lean"
