import PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_exponent_le
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_exponent_le
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_exponent_recurrence
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_exponent_recurrence
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_density_recurrence
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_density_recurrence
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_moment_even
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_moment_even
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_square_moment
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_square_moment
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_square_second
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_square_second
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_second_nonneg
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_second_nonneg
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_dyadic_strong
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.a21_dyadic_strong
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.manuscript_A21_actual
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A21DyadicMoment.manuscript_A21_actual

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A18OriginalGlobalInduction.actual_A18_original_global
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A18OriginalGlobalInduction.actual_A18_original_global
