import PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_rangeRestrict_surjective
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_rangeRestrict_surjective
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_flag_left_inverse
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_flag_left_inverse
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_flag_right_inverse
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_flag_right_inverse
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12SelectedFlagEquiv
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12SelectedFlagEquiv
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_endomorphism_range_surjective
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_endomorphism_range_surjective
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_submodule_card_le_end
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_submodule_card_le_end
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_selected_card_le
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_selected_card_le
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_energy_nonneg
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_energy_nonneg
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_filter_zero_above_support
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_filter_zero_above_support
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_energy_zero_above_support
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_energy_zero_above_support
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_energy_square_le
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_energy_square_le
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_energy_mean_eq_mass
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_energy_mean_eq_mass
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_Q_le_influence_mass
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_Q_le_influence_mass
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_selected_mass_bound
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_selected_mass_bound
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_influence_parameter_nonneg
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_influence_parameter_nonneg
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_Q_le
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.a12_Q_le
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.manuscript_A12_actual
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.manuscript_A12_actual
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.manuscript_A19_actual
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12InfluenceBound.manuscript_A19_actual

#check PvNP.RealizableHardness.ActualTypedABFullA16Final.filteredCarrierFunction_energy_le_A16
#print axioms PvNP.RealizableHardness.ActualTypedABFullA16Final.filteredCarrierFunction_energy_le_A16
