import PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AveragedTransportChecks
import PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AveragedAssemblyChecks
import PvNP.RealizableHardness.ActualBinaryMatrixHC46A8EnergyNaturalityChecks
import PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssemblyChecks
import PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AmbientAssemblyChecks
import PvNP.RealizableHardness.ActualBinaryMatrixHC46A8EndpointChecks
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AveragedTransport.a8_actual_T2_whole_function_expansion
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AveragedTransport.a8_actual_T2_complement_reconstruction
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AveragedTransport.a8_fixed_base_actual_energy_cube
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8OutputCoordinateTransport.a8T2ComplementDomainMap
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8OutputCoordinateTransport.a8T2ComplementKernelMap
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8OutputCoordinateTransport.a8_fixed_complement_t2_typed_fourier
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AveragedAssembly.a8_two_base_actual_averaged_transport
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AveragedAssembly.a8_actual_energy_zero_outside_supported_window
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8EnergyNaturality.a8_whole_typed_w6_derivative_naturality
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8EnergyNaturality.a8_typed_w6_energy_naturality
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8EnergyNaturality.a8_nested_actual_w6_energy_naturality
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_all_pair_sum_reindex
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_all_pair_actual_energy_reindex
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_nested_pair_sum_reindex
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_nested_frequency_eq_actual_final
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_complement_quotient_rank
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_complement_dimension_cost
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_nested_ambient_cost
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_nested_domain_incidence_iff
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_nested_range_incidence_iff
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8PairAssembly.a8_all_pair_actual_ambient_energy_reindex
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AmbientAssembly.a8_ambient_two_base_actual_averaged_transport
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AmbientAssembly.a8_ambient_output_pair_le_actual_complement_sum
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8AmbientAssembly.a8_ambient_output_pair_le_supported_complement_sum
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8Endpoint.a8_actual_coordinate_q_le_final_sum
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A8Endpoint.a8_output_q_le_actual_predecessor_sum
