import pathlib,json,hashlib,re
here=pathlib.Path(__file__).resolve().parent;parent=here/'full93-warning-candidate-v1/ActualSelectedComplementSourceSizeAnalyticMoment.lean';text=parent.read_text(encoding='utf-8')
start=text.index('theorem selected_actual_HC_spectral_moment_bound\n');end=text.index('def selected_actual_analytic_rhs ',start);helper=text[start:end]
helper=helper.replace('theorem selected_actual_HC_spectral_moment_bound\n','theorem selected_actual_HC_spectral_moment_bound_at_dyadic_exponent\n',1)
ceiling=' (hklt : k < 8 * m)';assert helper.count(ceiling)==1;helper=helper.replace(ceiling,'',1);assert 'hklt' not in helper
# Preserve the exact analytic statement except the name and upper-window premise.
inverse=helper.replace('theorem selected_actual_HC_spectral_moment_bound_at_dyadic_exponent\n','theorem selected_actual_HC_spectral_moment_bound\n',1).replace('(hkm : 4 * m â‰¤ k)\n','(hkm : 4 * m â‰¤ k)'+ceiling+'\n',1);assert inverse==text[start:end]
start=text.index('theorem selected_actual_material_moment_bound\n');finish=text.index('\nend\nend PvNP.RealizableHardness.',start);material=text[start:finish]
material=material.replace('theorem selected_actual_material_moment_bound\n','theorem selected_actual_material_moment_bound_at_dyadic_exponent\n',1)
material=material.replace('{N rows m L samplerA : Nat}','{N rows m L samplerA k : Nat}',1)
material=material.replace('(a : Real) (ha : 0 < a) :','(a : Real) (ha : 0 < a)\n    (hkDyadic : âˆƒ q : Nat, k = 2 ^ q) (hkm : 4 * m â‰¤ k) :',1)
a='    âˆƒ k q : Nat, k = 2 ^ q âˆ§ 4 * m â‰¤ k âˆ§ k < 8 * m âˆ§\n';assert material.count(a)==1;material=material.replace(a,'',1)
a='  rcases exists_dyadic_moment_exponent_window hm with âŸ¨k, q, hkpow, hkm, hkltâŸ©\n';assert material.count(a)==1;material=material.replace(a,'',1)
material=material.replace('have hMoment := selected_actual_HC_spectral_moment_bound\n','have hMoment := selected_actual_HC_spectral_moment_bound_at_dyadic_exponent\n',1).replace('ha hm hkm hklt\n','ha hm hkm\n',1).replace('hPR âŸ¨q, hkpowâŸ© hHC','hPR hkDyadic hHC',1)
a='  exact âŸ¨k, q, hkpow, hkm, hklt, hfinal, hCenterR.trans hBetaâŸ©';assert material.count(a)==1;material=material.replace(a,'  exact âŸ¨hfinal, hCenterR.trans hBetaâŸ©',1);assert 'hklt' not in material and 'hkpow' not in material
# Original-HC46 specialization removes only that analytic caller premise.
stmt_end=material.index(' := by\n');stmt=material[:stmt_end];assert stmt.count('    (hHC : HC46ExactContract)\n')==1
special=stmt.replace('theorem selected_actual_material_moment_bound_at_dyadic_exponent\n','theorem selected_actual_material_moment_bound_original_at_dyadic_exponent\n',1).replace('    (hHC : HC46ExactContract)\n','',1)
special+=' := by\n  exact selected_actual_material_moment_bound_at_dyadic_exponent I copies U A C T f\n    base sourceHeightCutoff hsel hA r hrd e he hfail\n    ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_exact hSpectral a ha hkDyadic hkm\n'
opens='\n'.join(line for line in text.split('set_option autoImplicit false',1)[0].splitlines() if line.startswith('open '))
prelude='import PvNP.RealizableHardness.ActualSelectedComplementSourceSizeAnalyticMoment\nimport PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant\n\n/-! Caller-chosen dyadic moment exponent, retaining the actual material lane.\nThe original fixed-window theorem remains unchanged. Uncompiled candidate. -/\nnamespace PvNP.RealizableHardness.ActualSelectedComplementManuscriptDyadicMoment\n'+opens+'\nopen ActualSelectedComplementSourceSizeAnalyticMoment\nset_option autoImplicit false\nnoncomputable section\nattribute [local instance] Classical.propDecidable\n\n'
data=(prelude+helper+'\n'+material+'\n\n'+special+'\nend\nend PvNP.RealizableHardness.ActualSelectedComplementManuscriptDyadicMoment\n').encode();dest=here/'manuscript-dyadic-moment-candidate-v1';dest.mkdir();name='ActualSelectedComplementManuscriptDyadicMoment.lean';(dest/name).write_bytes(data)
r={'schema':'manuscript-dyadic-material-consumer-source-candidate-v1','parent_analytic_candidate_sha256':hashlib.sha256(parent.read_bytes()).hexdigest().upper(),'candidate_sha256':hashlib.sha256(data).hexdigest().upper(),'bytes':len(data),'original_fixed_window_theorems_modified':False,'helper_exact_change':'Rename theorem; remove only upper ceiling k<8m. Identical proof and result. Native verification required.','material_exact_change':'Caller supplies dyadic kâ‰¥4m; same actual I/copies/U/A/C/T/f, guards, RHS and center identity; existential fixed-window packaging removed only for this new theorem.','HC46_specialization':'Original exact inhabitant supplied; remaining Spectral47 premise retained.','manuscript_parameter_order':'Manuscript inverse-explicit chooses Tâ‰¥max(4,4(m+3)/(m*rho)) and dyadic Pâ‰¥m*T; original4mâ‰¤k<8m is insufficient for this choice.','mathematical_validation_pending':True,'numeric_NO_proven':False,'local_compilation':False,'accepted':False,'launch_clearance':False};(dest/'derivation.json').write_text(json.dumps(r,indent=2)+'\n',encoding='utf-8');print(json.dumps(r))