import PvNP.RealizableHardness.ActualBinaryMatrixHC46A17TransposeHybridFilter

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A17TransposeHybridFilter

#check coordinateDualAnnihilator
#print axioms coordinateDualAnnihilator
#check coordinateDualAnnihilator_finrank
#print axioms coordinateDualAnnihilator_finrank
#check coordinateDualAnnihilator_finrank_one
#print axioms coordinateDualAnnihilator_finrank_one
#check transposeActualRestriction_domainFixed_eq_coordinateDualAnnihilator
#print axioms transposeActualRestriction_domainFixed_eq_coordinateDualAnnihilator
#check selected_bot_iff_coordinateDualAnnihilator_top
#print axioms selected_bot_iff_coordinateDualAnnihilator_top
#check complexAmbientHybridFilter_transpose_bot
#print axioms complexAmbientHybridFilter_transpose_bot
