import PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_energy_nonneg
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_energy_nonneg
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_projection_coefficient
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_projection_coefficient
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_projection_energy_mass
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_projection_energy_mass
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_projection_pairing
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_projection_pairing
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_projection_energy_le
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_projection_energy_le
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_zero_cost_energy
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_zero_cost_energy
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_dyadic_even
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_dyadic_even
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_dual_energy_of_influences
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_dual_energy_of_influences
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_positive_exponent
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.a22_positive_exponent
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.manuscript_A22_actual
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A22OriginalInduction.manuscript_A22_actual
