import PvNP.RealizableHardness.ActualStarBadMassWitness
import PvNP.RealizableHardness.ActualStarRelationCount
import Mathlib.Data.Fintype.EquivFin

/-! Support-indexed nonzero relations are reindexed to the accepted Fin-indexed
relation carrier before being counted. The relation/catalog objects are
selected independently of any sampled leaf tuple. -/

namespace PvNP.RealizableHardness.ActualStarSupportCatalog

open scoped BigOperators
open PvNP.RealizableHardness.GrassmannCounting
open PvNP.RealizableHardness.ActualSourceStarLaw
open PvNP.RealizableHardness.ActualStarRelationCount
open PvNP.RealizableHardness.ActualStarBadMassWitness

noncomputable section
attribute [local instance] Classical.propDecidable

/-- All-nonzero zero-sum vectors indexed by an actual finite support. -/
abbrev SupportRelation {A : Type*} [AddCommGroup A] {α : Type*}
    (S : Finset α) :=
  {v : S → A // (∀ i, v i ≠ 0) ∧ (∑ i, v i) = 0}

/-- Reindexing by the actual support equivalence `S ≃ Fin S.card` identifies
support-indexed relations with the accepted `NonzeroRelation` carrier. -/
def supportRelationEquiv {A : Type*} [AddCommGroup A] [Fintype A]
    {α : Type*} (S : Finset α) :
    NonzeroRelation (A := A) S.card ≃ SupportRelation (A := A) S := by
  classical
  let e : S ≃ Fin S.card := S.equivFin
  refine {
    toFun := fun r => ⟨fun i => r.1 (e i), ?_⟩
    invFun := fun v => ⟨fun i => v.1 (e.symm i), ?_⟩
    left_inv := ?_
    right_inv := ?_ }
  · constructor
    · intro i
      exact r.2.1 (e i)
    · calc
        (∑ i, r.1 (e i)) = ∑ i, r.1 i := Equiv.sum_comp e r.1
        _ = 0 := r.2.2
  · constructor
    · intro i
      exact v.2.1 (e.symm i)
    · calc
        (∑ i, v.1 (e.symm i)) = ∑ i, v.1 i := Equiv.sum_comp e.symm v.1
        _ = 0 := v.2.2
  · intro r
    apply Subtype.ext
    funext i
    simp [e]
  · intro v
    apply Subtype.ext
    funext i
    simp [e]

/-- The accepted relation-count bound transfers unchanged to any actual
support `S` after the explicit equivalence above. -/
theorem supportRelation_card_le_power {A : Type*} [AddCommGroup A] [Fintype A]
    {α : Type*} (S : Finset α) (hS : 2 ≤ S.card) :
    Fintype.card (SupportRelation (A := A) S) ≤
      (Fintype.card A - 1) ^ (S.card - 1) := by
  classical
  have hcount := nonzeroRelation_card_le_power (A := A) (n := S.card - 1)
  have hcard : (S.card - 1) + 1 = S.card := Nat.sub_add_cancel (by omega)
  calc
    Fintype.card (SupportRelation (A := A) S) =
        Fintype.card (NonzeroRelation (A := A) S.card) :=
      Fintype.card_congr (supportRelationEquiv (A := A) S).symm
    _ ≤ (Fintype.card A - 1) ^ (S.card - 1) := by
      simpa [hcard] using hcount

/-- Fixed-candidate quotient lines generated by a reindexed nonzero relation.
This function depends only on the support and relation, never on sampled
leaves. -/
def supportRelationLines {A : Type*} [AddCommGroup A] [Module (ZMod 2) A]
    [Fintype A]
    {α : Type*} (S : Finset α) (r : NonzeroRelation (A := A) S.card) :
    S → Grass A 1 := fun i =>
      quotientVectorLine ((supportRelationEquiv (A := A) S r).1 i)
        ((supportRelationEquiv (A := A) S r).2.1 i)

/-- Every compatible sampled star tuple belongs to the fixed-candidate line
event indexed by a preselected support relation. -/
theorem supportRelation_mem_supportedLineEvent
    {V : Type*} [AddCommGroup V] [Module (ZMod 2) V] [Finite V]
    {t d m : Nat} (htd : t ≤ d)
    (z : StarTuple (V := V) t d m) (S : Finset (Fin m))
    (hS : 2 ≤ S.card)
    [Fintype (V ⧸ z.1.val)]
    (r : NonzeroRelation (A := V ⧸ z.1.val) S.card)
    (hincrement : ∀ i : S,
      (supportRelationEquiv (A := V ⧸ z.1.val) S r).1 i ∈
        ActualStarJointKernel.incrementFamily z i.1) :
    z.2 ∈ ActualStarExtensionProduct.supportedLineEvent htd S z.1
      (supportRelationLines (A := V ⧸ z.1.val) S r) := by
  classical
  letI : Finite (V ⧸ z.1.val) :=
    Finite.of_surjective z.1.val.mkQ z.1.val.mkQ_surjective
  let q := supportRelationEquiv (A := V ⧸ z.1.val) S r
  have hbridge := exactSupport_relation_mem_supportedLineEvent
    (V := V) htd z S hS q.1 q.2.1 hincrement q.2.2
  exact hbridge.2

/-- A bad sampled tuple is contained in the event of at least one member of
the finite, preselected support/relation catalog. The selected index may be
extracted from the badness proof, but every catalog member and its event are
defined independently of the draw. -/
theorem not_jointlyDirect_has_catalogEvent
    {V : Type*} [AddCommGroup V] [Module (ZMod 2) V] [Finite V]
    {t d m : Nat} (htd : t ≤ d)
    (z : StarTuple (V := V) t d m)
    [Fintype (V ⧸ z.1.val)]
    (hbad : ¬ ActualSourceStarLaw.jointlyDirect z) :
    ∃ S : Finset (Fin m), 2 ≤ S.card ∧
      ∃ r : NonzeroRelation (A := V ⧸ z.1.val) S.card,
        z.2 ∈ ActualStarExtensionProduct.supportedLineEvent htd S z.1
          (supportRelationLines (A := V ⧸ z.1.val) S r) := by
  classical
  letI : Finite (V ⧸ z.1.val) :=
    Finite.of_surjective z.1.val.mkQ z.1.val.mkQ_surjective
  obtain ⟨S, hS, v, hnz, hincrement, hsum, _⟩ :=
    not_jointlyDirect_has_supportedLineEvent (V := V) htd z hbad
  let q : SupportRelation (A := V ⧸ z.1.val) S := ⟨v, hnz, hsum⟩
  let r : NonzeroRelation (A := V ⧸ z.1.val) S.card :=
    (supportRelationEquiv (A := V ⧸ z.1.val) S).symm q
  have htransport :
      (supportRelationEquiv (A := V ⧸ z.1.val) S r).1 = v := by
    have h := Equiv.apply_symm_apply (supportRelationEquiv (A := V ⧸ z.1.val) S) q
    exact congrArg Subtype.val h
  have hcompat : ∀ i : S,
      (supportRelationEquiv (A := V ⧸ z.1.val) S r).1 i ∈
        ActualStarJointKernel.incrementFamily z i.1 := by
    intro i
    rw [htransport]
    exact hincrement i
  refine ⟨S, hS, r, ?_⟩
  exact supportRelation_mem_supportedLineEvent (V := V) htd z S hS r hcompat

end
end PvNP.RealizableHardness.ActualStarSupportCatalog
