import PvNP.RealizableHardness.ActualStarJointKernel
import PvNP.RealizableHardness.ActualStarKernelSupport
import PvNP.RealizableHardness.ActualStarExtensionProduct

/-! A fixed-center bridge from full-joint kernel failure to an actual
supported quotient-line event.

This module stops before a probability union bound: it exposes the precise
candidate line event that a support-stratified first-moment argument must
count. It keeps the common center fixed and uses the full direct-sum kernel.
-/

namespace PvNP.RealizableHardness.ActualStarBadMassWitness

open scoped BigOperators
open PvNP.RealizableHardness.GrassmannCounting
open PvNP.RealizableHardness.GrassmannFlagPosterior
open PvNP.RealizableHardness.ActualFiniteLaw
open PvNP.RealizableHardness.ActualSourceStarLaw
open PvNP.RealizableHardness.ActualStarJointKernel
open PvNP.RealizableHardness.ActualStarKernelSupport
open PvNP.RealizableHardness.ActualStarExtensionProduct

noncomputable section
attribute [local instance] Classical.propDecidable

variable {V : Type*} [AddCommGroup V] [Module (ZMod 2) V] [Finite V]
variable {t d m : Nat}

/-- The one-dimensional quotient subspace generated by a nonzero vector. -/
def quotientVectorLine {A : Type*} [AddCommGroup A] [Module (ZMod 2) A]
    (v : A) (hv : v ≠ 0) : Grass A 1 :=
  ⟨(ZMod 2) ∙ v, finrank_span_singleton hv⟩

/-- An exact-support relation on actual quotient increments determines a
line event for the same ordered leaves over their common center. -/
theorem exactSupport_relation_mem_supportedLineEvent
    (htd : t ≤ d) (z : StarTuple (V := V) t d m)
    (S : Finset (Fin m)) (hS : 2 ≤ S.card)
    (v : S → (V ⧸ z.1.val))
    (hnz : ∀ i, v i ≠ 0)
    (hincrement : ∀ i, v i ∈ incrementFamily z i.1)
    (hsum : (∑ i : S, v i) = 0) :
    (∀ i, (quotientVectorLine (v i) (hnz i)).val ≤
        (upperQuotientEquiv z.1 htd (z.2 i.1)).val) ∧
      z.2 ∈ supportedLineEvent (V := V) htd S z.1
        (fun i => quotientVectorLine (v i) (hnz i)) := by
  letI : Finite (V ⧸ z.1.val) :=
    Finite.of_surjective z.1.val.mkQ z.1.val.mkQ_surjective
  letI : Fintype (V ⧸ z.1.val) := Fintype.ofFinite _
  have hcontained (i : S) :
      (quotientVectorLine (v i) (hnz i)).val ≤
        (upperQuotientEquiv z.1 htd (z.2 i.1)).val := by
    change (ZMod 2 ∙ v i) ≤ incrementFamily z i.1
    exact (Submodule.span_singleton_le_iff_mem _ _).2 (hincrement i)
  refine ⟨hcontained, ?_⟩
  · simpa only [supportedLineEvent, Finset.mem_filter, Finset.mem_univ, true_and]
      using hcontained

/-- A failure of the actual full-joint directness predicate yields an
all-nonzero relation supported on at least two leaves, and its generated
quotient lines are contained in those same leaves. -/
theorem not_jointlyDirect_has_supportedLineEvent
    (htd : t ≤ d) (z : StarTuple (V := V) t d m)
    (hbad : ¬ jointlyDirect z) :
    ∃ S : Finset (Fin m), 2 ≤ S.card ∧
      ∃ v : S → (V ⧸ z.1.val),
        (∀ i, v i ≠ 0) ∧
        (∀ i, v i ∈ incrementFamily z i.1) ∧
        (∑ i : S, v i) = 0 ∧
        ∀ hv : ∀ i, v i ≠ 0,
          (∀ i, (quotientVectorLine (v i) (hv i)).val ≤
            (upperQuotientEquiv z.1 htd (z.2 i.1)).val) ∧
          z.2 ∈ supportedLineEvent (V := V) htd S z.1
            (fun i => quotientVectorLine (v i) (hv i)) := by
  obtain ⟨x, hx, hker⟩ :=
    (not_jointlyDirect_iff_nonzero_incrementKernel
      (V := V) (t := t) (d := d) (m := m) z).mp hbad
  obtain ⟨S, hS, v, hnz, hincrement, hsum⟩ :=
    kernelWitness_has_exact_support_relation z x hx hker
  have hline := exactSupport_relation_mem_supportedLineEvent
    (V := V) (t := t) (d := d) (m := m) htd z S hS v hnz hincrement hsum
  refine ⟨S, hS, v, hnz, hincrement, hsum, ?_⟩
  intro hv
  have hproof (i : S) : hv i = hnz i := Subsingleton.elim _ _
  have hlines : ∀ i, (quotientVectorLine (v i) (hv i)).val ≤
      (upperQuotientEquiv z.1 htd (z.2 i.1)).val := by
    intro i
    rw [hproof i]
    exact hline.1 i
  have hevent : z.2 ∈ supportedLineEvent (V := V) htd S z.1
      (fun i => quotientVectorLine (v i) (hv i)) := by
    have hfun : (fun i => quotientVectorLine (v i) (hv i)) =
        (fun i => quotientVectorLine (v i) (hnz i)) := by
      funext i
      rw [hproof i]
    rw [hfun]
    exact hline.2
  exact ⟨hlines, hevent⟩

/-- Exact fixed-center mass for the line event generated by any all-nonzero
supported quotient relation. This composes only the conditional ordered leaf
law; it does not multiply unconditional leaves or average over centers. -/
theorem fixedCenter_relationLineEvent_mass
    (htd : t ≤ d) (hdV : d ≤ Module.finrank (ZMod 2) V)
    (hk : 1 ≤ d - t)
    (U : Grass V t) (witness : Fin m → Extension U d)
    (S : Finset (Fin m)) (v : S → (V ⧸ U.val))
    (hnz : ∀ i, v i ≠ 0)
    (hsum : (∑ i : S, v i) = 0) :
    eventMass (extensionTupleLaw (V := V) (t := t) (d := d) U witness)
        (supportedLineEvent (V := V) htd S U
          (fun i => quotientVectorLine (v i) (hnz i))) =
      ((gaussian (d - t) 1 : ℚ) /
        gaussian (Module.finrank (ZMod 2) (V ⧸ U.val)) 1) ^ S.card := by
  letI : Finite (V ⧸ U.val) :=
    Finite.of_surjective U.val.mkQ U.val.mkQ_surjective
  letI : Fintype (V ⧸ U.val) := Fintype.ofFinite _
  exact fixedCenter_supportedLine_eventMass (V := V) htd hdV hk U witness S
    (fun i => quotientVectorLine (v i) (hnz i))

end
end PvNP.RealizableHardness.ActualStarBadMassWitness
