import PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_boolean_second
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_boolean_second
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_boolean_mean_le_one
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_boolean_mean_le_one
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_boolean_zero_of_energy_zero
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_boolean_zero_of_energy_zero
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_moment_density_algebra
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_moment_density_algebra
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_moment_to_norm
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_moment_to_norm
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_exact
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46OriginalExactInhabitant.original_HC46_exact
