import {test} from 'node:test';
import assert from 'node:assert/strict';
import {policy,same,rootGate,ensurePolicy,validateBoundary,PACKET_HASH,BUCKET} from './control.mjs';
const simulate=({initial=null,lost=false,readbackFails=false,priorIntent=false}={})=>{
  let current=initial,attempts=0,prepared=0,reads=0;
  return {run:()=>ensurePolicy({get:async()=>{reads++;if(readbackFails&&attempts)throw Error('readback-unavailable');return current;},put:async p=>{attempts++;current=p;if(lost)throw Error('lost-reply');},boundary:async()=>{},prepare:async()=>{prepared++;},priorIntent}),counts:()=>({attempts,prepared,reads})};
};
test('restores global deny with both destination ARNs and no Allow grants',async()=>{const s=simulate();const r=await s.run();assert.equal(r.sdk_mutation_attempts,1);assert.deepEqual(rootGate(r.readback),{https_deny:true,source_migration_grants:false,statements:1});assert.equal(policy.Statement[0].Principal,'*');assert.equal(policy.Statement[0].Action,'s3:*');assert.equal(policy.Statement[0].Condition.Bool['aws:SecureTransport'],'false');assert.deepEqual(policy.Statement[0].Resource,[`arn:aws:s3:::${BUCKET}`,`arn:aws:s3:::${BUCKET}/*`]);});
test('all source/migration Allow variants are refused before mutation',async()=>{for(const principal of ['*',{AWS:'arn:aws:iam::485386182336:user/cyint-ea'}])for(const action of ['s3:*','s3:PutObject','s3:PutObjectTagging']){const s=simulate({initial:{Version:'2012-10-17',Statement:[...policy.Statement,{Effect:'Allow',Principal:principal,Action:action,Resource:`arn:aws:s3:::${BUCKET}/*`}]}});await assert.rejects(s.run(),/unexpected-unrelated-policy/);assert.equal(s.counts().attempts,0);}});
test('unrelated Deny and changed baseline are refused',async()=>{for(const p of [{Statement:[]},{...policy,Statement:[{...policy.Statement[0],Action:'s3:GetObject'}]}]){const s=simulate({initial:p});await assert.rejects(s.run(),/unexpected-unrelated-policy/);assert.equal(s.counts().attempts,0);}});
test('idempotent replay preserves baseline with zero writes',async()=>{const s=simulate({initial:structuredClone(policy),priorIntent:true});assert.equal((await s.run()).operation,'conditional-noop');assert.equal(s.counts().attempts,0);assert.equal(s.counts().prepared,0);});
test('lost mutation reply reconciles by readback with one attempt',async()=>{const s=simulate({lost:true});assert.equal((await s.run()).lost_reply,true);assert.equal(s.counts().attempts,1);});
test('lost readback fails closed without replay',async()=>{const s=simulate({lost:true,readbackFails:true});await assert.rejects(s.run(),/readback-unavailable/);assert.equal(s.counts().attempts,1);});
test('prior unresolved intent forbids another absent-policy put',async()=>{const s=simulate({priorIntent:true});await assert.rejects(s.run(),/prior-mutation-intent/);assert.equal(s.counts().attempts,0);});
test('root gate rejects missing HTTPS, temporary grants, wrong bucket and weak scope',()=>{for(const p of [null,{Statement:[]},{...policy,Statement:[{...policy.Statement[0],Resource:'arn:aws:s3:::other/*'}]},{...policy,Statement:[{...policy.Statement[0],Principal:{AWS:'arn:aws:iam::063280428495:root'}}]}])assert.throws(()=>rootGate(p),/destination-https-baseline-required/);});
test('boundary rejects live actor, incomplete packet and unbound bridge',()=>{const bridge={absent:true},bridgeHash='a'.repeat(64),packet={type:'archive-author-fullscope-v1',complete:true,versions:205,core_chunks:51,recovery_unique_chunks:54,recovery_catalogs:44,catalogs:Array(45).fill({}),restore:{verified:true,bucket:BUCKET},bridge,artifacts:[{file:'x/repair/temporary-copy-policy-removal.json',sha256:bridgeHash}]},b={alive:false,locks:false,status:{pid:13356,phase:'author-complete-awaiting-root-acceptance',packet_sha256:PACKET_HASH},packet,packetHash:PACKET_HASH,bridge,bridgeHash};validateBoundary(b);for(const change of [{alive:true},{locks:true},{packet:{...packet,versions:204}},{bridgeHash:'b'.repeat(64)},{packetHash:'c'.repeat(64)}])assert.throws(()=>validateBoundary({...b,...change}));});
test('policy changed between preflight and put is refused',async()=>{let calls=0,writes=0;await assert.rejects(ensurePolicy({get:async()=>++calls===1?null:policy,put:async()=>{writes++;},boundary:async()=>{},prepare:async()=>{}}),/policy-changed-before-mutation/);assert.equal(writes,0);});
test('failed put with absent readback cannot claim enforcement',async()=>{let attempts=0;await assert.rejects(ensurePolicy({get:async()=>null,put:async()=>{attempts++;throw Error();},boundary:async()=>{},prepare:async()=>{}}),/destination-https-baseline-required/);assert.equal(attempts,1);});
test('canonical equality tolerates object ordering but never added statements',()=>{assert(same(policy,JSON.parse(JSON.stringify(policy))));assert(!same(policy,{...policy,Statement:[...policy.Statement,...policy.Statement]}));});
