import PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6ActualPhiGram
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_phi_gram_nonneg
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_phi_gram_frobenius_le_mass
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_phi_coefficient_mass_le_parseval
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_f1_pair_le_gram_sum
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_f1_total_energy_le_parseval
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_f1_total_energy_le
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_phi_gram_nonneg
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_phi_gram_frobenius_le_mass
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_phi_coefficient_mass_le_parseval
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_f1_pair_le_gram_sum
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_f1_total_energy_le_parseval
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46DR6SignMoments.dr6_actual_f1_total_energy_le
