import PvNP.RealizableHardness.ActualFiniteBinaryImageOrbitFourier

#check PvNP.RealizableHardness.ActualFiniteBinaryImageOrbitFourier.exists_right_action_same_image
#print axioms PvNP.RealizableHardness.ActualFiniteBinaryImageOrbitFourier.exists_right_action_same_image
#check PvNP.RealizableHardness.ActualFiniteBinaryImageOrbitFourier.fourierCoeff_rankProjection_eq_same_image
#print axioms PvNP.RealizableHardness.ActualFiniteBinaryImageOrbitFourier.fourierCoeff_rankProjection_eq_same_image
