import PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse

#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.filteredCarrierFunction
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.hyperplane_suffix_A1_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.hyperplane_suffix_A1_collapse
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.line_suffix_A1_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.line_suffix_A1_collapse
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_line_head_A1_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_line_head_A1_collapse
#check PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_hyperplane_head_A1_collapse
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalDCollapse.canonical_hyperplane_head_A1_collapse
