import PvNP.RealizableHardness.ActualBinaryMatrixHC46CommonDerivative

open PvNP.RealizableHardness.ActualBinaryMatrixHC46CommonDerivative

#check complexHybridLineDerivative_add
#print axioms complexHybridLineDerivative_add
#check complexHyperplaneDerivative_add
#print axioms complexHyperplaneDerivative_add
#check complexRankProjection_idempotent
#print axioms complexRankProjection_idempotent
#check coordinateLineDerivativeChain_eq_projected_common
#print axioms coordinateLineDerivativeChain_eq_projected_common
#check coordinateHyperplaneDerivativeChain_eq_projected_common
#print axioms coordinateHyperplaneDerivativeChain_eq_projected_common
#check commonLineDerivativeChain_pure_rank
#print axioms commonLineDerivativeChain_pure_rank
#check commonHyperplaneDerivativeChain_pure_rank
#print axioms commonHyperplaneDerivativeChain_pure_rank
#check mixedCoordinateDerivativeChain_eq_projected_common
#print axioms mixedCoordinateDerivativeChain_eq_projected_common
