import PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps

#check PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.line_step_hybrid_selector
#print axioms PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.line_step_hybrid_selector
#check PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.hyperplane_step_hybrid_selector
#print axioms PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.hyperplane_step_hybrid_selector
#check PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.selected_affine_phase_factor
#print axioms PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.selected_affine_phase_factor
#check PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.typed_line_A1_operator_step
#print axioms PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.typed_line_A1_operator_step
#check PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.typed_hyperplane_A1_operator_step
#print axioms PvNP.RealizableHardness.ActualTypedABHybridSelectorSteps.typed_hyperplane_A1_operator_step
