import PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics

#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.manuscriptAgreementFloor
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.manuscriptMomentThreshold
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.sourceHolderLowerBound
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.acceptedInverseDecayCoefficient
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.manuscriptInverseDecayCoefficient
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.fixed_rho_explicit
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_radius_rho_product
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.manuscript_threshold_simplifies
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.accepted_window_decay_is_negative
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.manuscript_large_dyadic_choices
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.manuscript_large_holder_decay_positive
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_holder_ratio_le_inverse
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_holder_decay_dominates_source
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_actual_HC_spectral_moment_bound_large_dyadic
#check PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_actual_material_moment_bound_large_dyadic

#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.fixed_rho_explicit
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_radius_rho_product
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.manuscript_threshold_simplifies
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.accepted_window_decay_is_negative
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.manuscript_large_dyadic_choices
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.manuscript_large_holder_decay_positive
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_holder_ratio_le_inverse
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_holder_decay_dominates_source
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_actual_HC_spectral_moment_bound_large_dyadic
#print axioms PvNP.RealizableHardness.ActualSelectedComplementAnalyticNumerics.selected_actual_material_moment_bound_large_dyadic
