import PvNP.RealizableHardness.ActualTypedABCanonicalProjection

#check PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_line_successor_projection
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_line_successor_projection
#check PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_hyperplane_successor_projection
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_hyperplane_successor_projection
#check PvNP.RealizableHardness.ActualTypedABCanonicalProjection.applyCanonicalFilters
#check PvNP.RealizableHardness.ActualTypedABCanonicalProjection.ranked_terminal_projection_eq_canonicalFilters
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalProjection.ranked_terminal_projection_eq_canonicalFilters
#check PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_source_tower_projection_eq_filters
#print axioms PvNP.RealizableHardness.ActualTypedABCanonicalProjection.canonical_source_tower_projection_eq_filters
