import PvNP.RealizableHardness.ActualTypedABFullA16Assembly

open PvNP.RealizableHardness.ActualTypedABFullA16Assembly

#check filteredCarrierFunction_reconstruct_range_of_support
#print axioms filteredCarrierFunction_reconstruct_range_of_support
#check selected_frequency_rank_lower_bound
#print axioms selected_frequency_rank_lower_bound
#check filteredCarrierFunction_rankProjection_zero_of_below_carrier
#print axioms filteredCarrierFunction_rankProjection_zero_of_below_carrier
#check filteredCarrierFunction_rankProjection_energy_bound
#print axioms filteredCarrierFunction_rankProjection_energy_bound
#check filteredCarrierFunction_parameter_nonneg
#print axioms filteredCarrierFunction_parameter_nonneg
#check typedComplexRankProjection_cross_orthogonal
#print axioms typedComplexRankProjection_cross_orthogonal
#check carrierEnergy_finite_sum_of_orthogonal
#print axioms carrierEnergy_finite_sum_of_orthogonal
