import PvNP.RealizableHardness.ActualTypedABArbitraryRankProjection

#check PvNP.RealizableHardness.ActualTypedABArbitraryRankProjection.zero_total_flag_length_endpoints
#print axioms PvNP.RealizableHardness.ActualTypedABArbitraryRankProjection.zero_total_flag_length_endpoints
#check PvNP.RealizableHardness.ActualTypedABArbitraryRankProjection.arbitrary_carrier_rank_projection_identity
#print axioms PvNP.RealizableHardness.ActualTypedABArbitraryRankProjection.arbitrary_carrier_rank_projection_identity
