import PvNP.RealizableHardness.ActualBinaryMatrixHC46A17DerivativeGlobalTransfer

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A17DerivativeGlobalTransfer

#check fixedDomainDerivativeCoordinate
#print axioms fixedDomainDerivativeCoordinate
#check actual_derivative_global_implies_typed
#print axioms actual_derivative_global_implies_typed
#check actual_fixed_domain_derivative_to_typed_global
#print axioms actual_fixed_domain_derivative_to_typed_global
#check actual_fixed_domain_derivative_carrier_fibre_energy_le
#print axioms actual_fixed_domain_derivative_carrier_fibre_energy_le
#check actual_fixed_domain_derivative_lift_fibre_energy_le
#print axioms actual_fixed_domain_derivative_lift_fibre_energy_le
#check actual_fixed_domain_lift_order
#print axioms actual_fixed_domain_lift_order
