import PvNP.RealizableHardness.ActualBinaryMatrixHC46A17GenericParentEnergy

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A17GenericParentEnergy

#check actual_derivative_bounds_every_parent_unit_cost
#print axioms actual_derivative_bounds_every_parent_unit_cost
