import PvNP.RealizableHardness.ActualBinaryMatrixHC46A18OriginalGlobalInduction

open PvNP.RealizableHardness.ActualBinaryMatrixHC46A18OriginalGlobalInduction

#check OriginalActualInfluenceThrough
#print axioms OriginalActualInfluenceThrough
#check original_influence_order_zero_seed
#print axioms original_influence_order_zero_seed
#check original_influence_parameter_nonneg
#print axioms original_influence_parameter_nonneg
#check original_influence_rank_projection
#print axioms original_influence_rank_projection
#check a18UniformMean
#print axioms a18UniformMean
#check original_influence_line_A1_mean
#print axioms original_influence_line_A1_mean
#check original_influence_hyperplane_A1_mean
#print axioms original_influence_hyperplane_A1_mean
#check original_influence_A1_composition_mean
#print axioms original_influence_A1_composition_mean
#check original_influence_A1_relative_mean
#print axioms original_influence_A1_relative_mean
#check relative_endpoint_cost_add
#print axioms relative_endpoint_cost_add
#check original_influence_order_one_relative_reduction
#print axioms original_influence_order_one_relative_reduction
#check complexCarrierHybridFilter_coordinate
#print axioms complexCarrierHybridFilter_coordinate
#check carrierCoordinateDomainQuotientEquiv
#print axioms carrierCoordinateDomainQuotientEquiv
#check carrierCoordinateCodomainEquiv
#print axioms carrierCoordinateCodomainEquiv
#check carrierCoordinateNestedHomEquiv
#print axioms carrierCoordinateNestedHomEquiv
#check carrierCoordinateBaseLift
#print axioms carrierCoordinateBaseLift
#check carrierCoordinate_affineMatrix
#print axioms carrierCoordinate_affineMatrix
#check actualDerivativeCoordinate_nestedFilter
#print axioms actualDerivativeCoordinate_nestedFilter
#check actualDerivativeCoordinate_nestedMean
#print axioms actualDerivativeCoordinate_nestedMean
#check original_influence_order_one_derivativeCoordinate_reduction
#print axioms original_influence_order_one_derivativeCoordinate_reduction
#check actual_A18_original_global
#print axioms actual_A18_original_global
