import PvNP.RealizableHardness.ActualBinaryMatrixHC46A12FourthMoment

#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12FourthMoment.complex_fourier_parseval
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12FourthMoment.complex_fourier_parseval
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12FourthMoment.actual_affine_base_energy_eq_selected_fourier_mass
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12FourthMoment.actual_affine_base_energy_eq_selected_fourier_mass
#check PvNP.RealizableHardness.ActualBinaryMatrixHC46A12FourthMoment.actual_affine_derivative_energy_eq_selected_fourier_mass
#print axioms PvNP.RealizableHardness.ActualBinaryMatrixHC46A12FourthMoment.actual_affine_derivative_energy_eq_selected_fourier_mass
