import PvNP.RealizableHardness.ActualBinaryMatrixHC46PA4Transport

open PvNP.RealizableHardness.ActualBinaryMatrixHC46PA4Transport

#check typedLineCoordinateOutput
#check typedLineCoordinateShift
#check typedLineReducedWitness_eq_coordinate_shift
#check typedLineReducedWitness_global_of_coordinate
#check typedHyperplaneCoordinateOutput
#check typedHyperplaneCoordinateShift
#check typedHyperplaneReducedWitness_eq_coordinate_shift
#check typedHyperplaneReducedWitness_global_of_coordinate
#print axioms typedLineReducedWitness_eq_coordinate_shift
#print axioms typedLineReducedWitness_global_of_coordinate
#print axioms typedHyperplaneReducedWitness_eq_coordinate_shift
#print axioms typedHyperplaneReducedWitness_global_of_coordinate
#check PvNP.RealizableHardness.BinaryMatrixTypedA15ReducedGlobal.typed_line_oneStep_A15_global
#check PvNP.RealizableHardness.BinaryMatrixTypedA15HyperplaneReducedGlobal.typed_hyperplane_oneStep_A15_global
#print axioms PvNP.RealizableHardness.BinaryMatrixTypedA15ReducedGlobal.typed_line_oneStep_A15_global
#print axioms PvNP.RealizableHardness.BinaryMatrixTypedA15HyperplaneReducedGlobal.typed_hyperplane_oneStep_A15_global
